"use strict";

document.addEventListener("DOMContentLoaded", () => {
	const canvas = document.querySelector("#race-canvas");
	const context = canvas.getContext("2d");
	const trackMessage = document.querySelector("#track-message");
	const startButton = document.querySelector("#start-button");
	const pauseButton = document.querySelector("#pause-button");
	const speedControl = document.querySelector("#speed-control");
	const speedLabel = document.querySelector("#speed-label");
	const distanceElement = document.querySelector("#distance");
	const creditsElement = document.querySelector("#credits");
	const comboElement = document.querySelector("#combo");
	const speedElement = document.querySelector("#speed-readout");
	const rewardElement = document.querySelector("#reward-total");
	const progressElement = document.querySelector("#reward-progress");
	const bestScoreElement = document.querySelector("#best-score");

	const state = { running: false, paused: false, lastTime: 0, roadOffset: 0, distance: 0, credits: 0, combo: 1, score: 0, speed: 72, playerX: 0.5, traffic: [], pickups: [], sparks: [] };
	const keys = { left: false, right: false };
	const bestScore = Number(localStorage.getItem("neon-apex-best") || 0);
	bestScoreElement.textContent = String(bestScore).padStart(6, "0");

	function resizeCanvas() { const ratio = window.devicePixelRatio || 1; canvas.width = canvas.clientWidth * ratio; canvas.height = canvas.clientHeight * ratio; context.setTransform(ratio, 0, 0, ratio, 0, 0); }
	function roadMetrics() { const width = canvas.clientWidth; return { width, height: canvas.clientHeight, roadWidth: Math.min(width * .7, 420), left: (width - Math.min(width * .7, 420)) / 2 }; }
	function spawnObjects() { state.traffic = []; state.pickups = []; for (let index = 0; index < 5; index += 1) state.traffic.push({ lane: Math.floor(Math.random() * 3), y: -index * 180 - 100, color: index % 2 ? "#ff6a3d" : "#59d3d3", speed: .7 + Math.random() * .5 }); for (let index = 0; index < 7; index += 1) state.pickups.push({ lane: Math.floor(Math.random() * 3), y: -index * 270 - 80, kind: index % 4 === 0 ? "boost" : "credit" }); }
	function laneX(lane, metrics) { return metrics.left + metrics.roadWidth * ((lane + .5) / 3); }
	function drawCar(x, y, color, player = false) { context.save(); context.translate(x, y); context.shadowBlur = player ? 22 : 12; context.shadowColor = color; context.fillStyle = "#07131d"; context.fillRect(-17, -31, 34, 62); context.fillStyle = color; context.fillRect(-13, -28, 26, 56); context.fillStyle = player ? "#edf3f6" : "#111f2a"; context.fillRect(-9, -14, 18, 17); context.fillStyle = "#ffcf6e"; context.fillRect(-10, -25, 7, 4); context.fillRect(3, -25, 7, 4); context.fillStyle = player ? "#ff6a3d" : "#ef5365"; context.fillRect(-10, 21, 7, 4); context.fillRect(3, 21, 7, 4); context.restore(); }
	function drawScene() { const metrics = roadMetrics(); const center = metrics.width / 2; context.fillStyle = "#102a35"; context.fillRect(0, 0, metrics.width, metrics.height); context.fillStyle = "#183d43"; context.fillRect(0, 0, metrics.left, metrics.height); context.fillRect(metrics.left + metrics.roadWidth, 0, metrics.left, metrics.height); context.fillStyle = "#202f3a"; context.fillRect(metrics.left, 0, metrics.roadWidth, metrics.height); context.fillStyle = "#ff6a3d"; context.fillRect(metrics.left, 0, 4, metrics.height); context.fillRect(metrics.left + metrics.roadWidth - 4, 0, 4, metrics.height); context.setLineDash([30, 26]); context.lineDashOffset = state.roadOffset; context.strokeStyle = "rgba(237,243,246,.42)"; context.lineWidth = 3; for (let lane = 1; lane < 3; lane += 1) { context.beginPath(); context.moveTo(metrics.left + metrics.roadWidth * lane / 3, 0); context.lineTo(metrics.left + metrics.roadWidth * lane / 3, metrics.height); context.stroke(); } context.setLineDash([]); state.pickups.forEach((item) => { const x = laneX(item.lane, metrics); const y = item.y; context.save(); context.translate(x, y); context.rotate(Math.PI / 4); context.fillStyle = item.kind === "boost" ? "#ff6a3d" : "#d7f25b"; context.shadowColor = context.fillStyle; context.shadowBlur = 15; context.fillRect(-8, -8, 16, 16); context.restore(); }); state.traffic.forEach((car) => drawCar(laneX(car.lane, metrics), car.y, car.color)); drawCar(metrics.left + metrics.roadWidth * state.playerX, metrics.height - 88, "#d7f25b", true); state.sparks.forEach((spark) => { context.fillStyle = spark.color; context.globalAlpha = spark.life; context.fillRect(spark.x, spark.y, 3, 3); }); context.globalAlpha = 1; }
	function update(delta) { const metrics = roadMetrics(); const roadSpeed = state.speed * .052; state.roadOffset = (state.roadOffset + roadSpeed * delta) % 56; state.distance += state.speed * delta / 1000 * .18; state.score = Math.floor(state.distance * (1 + state.combo * .15)); if (keys.left) state.playerX -= delta * .0012; if (keys.right) state.playerX += delta * .0012; state.playerX = Math.max(.08, Math.min(.92, state.playerX)); state.traffic.forEach((car) => { car.y += roadSpeed * car.speed * delta; if (car.y > metrics.height + 70) { car.y = -80 - Math.random() * 180; car.lane = Math.floor(Math.random() * 3); } }); state.pickups.forEach((item) => { item.y += roadSpeed * delta; if (item.y > metrics.height + 40) { item.y = -100 - Math.random() * 300; item.lane = Math.floor(Math.random() * 3); } }); const playerY = metrics.height - 88; state.traffic.forEach((car) => { const carPosition = (car.lane + .5) / 3; if (Math.abs(car.y - playerY) < 48 && Math.abs(carPosition - state.playerX) < .11) endRun(); }); state.pickups.forEach((item) => { if (Math.abs(item.y - playerY) < 42 && Math.abs((item.lane + .5) / 3 - state.playerX) < .11) { item.y = -600; if (item.kind === "boost") state.combo = Math.min(5, state.combo + .6); else { state.credits += 1; state.combo = Math.min(5, state.combo + .15); if (state.credits % 10 === 0) state.combo = Math.min(5, state.combo + 1); } } }); state.combo = Math.max(1, state.combo - delta * .00003); state.sparks = state.sparks.filter((spark) => { spark.y += delta * .04; spark.life -= delta * .002; return spark.life > 0; }); distanceElement.textContent = String(Math.floor(state.distance)).padStart(4, "0"); creditsElement.textContent = String(state.credits).padStart(3, "0"); comboElement.textContent = `x${state.combo.toFixed(1)}`; rewardElement.textContent = `+${String(Math.floor(state.score * .1)).padStart(3, "0")}`; progressElement.style.width = `${(state.credits % 10) * 10}%`; }
	function frame(time) { const delta = Math.min(40, time - state.lastTime || 16); state.lastTime = time; if (state.running && !state.paused) update(delta); drawScene(); if (state.running) requestAnimationFrame(frame); }
	function startRun() { state.running = true; state.paused = false; state.distance = 0; state.credits = 0; state.combo = 1; state.score = 0; state.playerX = .5; speedElement.textContent = state.speed; trackMessage.classList.add("hidden"); pauseButton.innerHTML = "Pause <span>II</span>"; spawnObjects(); requestAnimationFrame(frame); }
	function endRun() { state.running = false; const finalScore = Math.floor(state.score); const currentBest = Math.max(bestScore, finalScore); localStorage.setItem("neon-apex-best", currentBest); bestScoreElement.textContent = String(currentBest).padStart(6, "0"); trackMessage.querySelector(".message-kicker").textContent = "RUN COMPLETE"; trackMessage.querySelector("h2").innerHTML = `${finalScore}<br /><em>points.</em>`; trackMessage.querySelector("p:last-of-type").textContent = "Traffic got the better line. Reset your pace and run it back."; startButton.innerHTML = "Run it back <span>-></span>"; trackMessage.classList.remove("hidden"); }
	startButton.addEventListener("click", startRun); pauseButton.addEventListener("click", () => { if (!state.running) return; state.paused = !state.paused; pauseButton.innerHTML = state.paused ? "Resume <span>></span>" : "Pause <span>II</span>"; }); speedControl.addEventListener("input", (event) => { state.speed = Number(event.target.value); speedLabel.textContent = `${state.speed} km/h`; speedElement.textContent = state.speed; event.target.style.background = `linear-gradient(90deg, var(--lime) ${((state.speed - 45) / 75) * 100}%, #294452 ${((state.speed - 45) / 75) * 100}%)`; }); window.addEventListener("resize", resizeCanvas); window.addEventListener("keydown", (event) => { if (["ArrowLeft", "a", "A"].includes(event.key)) keys.left = true; if (["ArrowRight", "d", "D"].includes(event.key)) keys.right = true; }); window.addEventListener("keyup", (event) => { if (["ArrowLeft", "a", "A"].includes(event.key)) keys.left = false; if (["ArrowRight", "d", "D"].includes(event.key)) keys.right = false; }); resizeCanvas(); drawScene();
});
